#!/usr/bin/env pwsh
# Host-side firmware flasher (Windows PowerShell / PowerShell 7+).
#
# The Docker build image cannot flash the board: Docker Desktop on Windows/macOS
# has no USB/COM passthrough, so `pio run -t upload` inside the container never
# sees the device. Instead, build with .\build.ps1 and flash the resulting
# artifacts from the host with esptool (the only host prerequisite).
#
# Prerequisite:
#   uv tool install esptool        (or: pipx install esptool / pip install esptool)
#
# Usage:
#   .\build.ps1                    # build in Docker first
#   .\flash.ps1                    # auto-detect the COM port and flash
#   .\flash.ps1 -Port COM7         # explicit port
#   .\flash.ps1 -Baud 460800       # slower baud if 921600 is flaky
#
# Put the board in bootloader mode first: hold BOOT, tap RESET, release BOOT.
# (The single USB-C port is the USB-OTG port, and the firmware claims it for
# HID, so the board must be in ROM download mode to be flashable.)
[CmdletBinding()]
param(
    [string]$Port,
    [int]$Baud = 921600,
    [string]$Environment = 'feather_s3_idf'
)

$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BuildDir = Join-Path $ScriptDir ".pio\build\$Environment"

# Offsets mirror .pio\build\<env>\flash_args generated by ESP-IDF.
$Images = [ordered]@{
    '0x0'     = Join-Path $BuildDir 'bootloader.bin'
    '0x8000'  = Join-Path $BuildDir 'partitions.bin'
    '0x10000' = Join-Path $BuildDir 'firmware.bin'
}

$missing = $Images.Values | Where-Object { -not (Test-Path $_) }
if ($missing) {
    Write-Error @"
Missing build artifacts:
  $($missing -join "`n  ")
Run .\build.ps1 first.
"@
    exit 1
}

# esptool ships as `esptool.py` (v4) or `esptool` (v5); fall back to the module.
$exe = $null
$preArgs = @()
foreach ($candidate in 'esptool.py', 'esptool') {
    if (Get-Command $candidate -ErrorAction SilentlyContinue) { $exe = $candidate; break }
}
if (-not $exe) {
    foreach ($py in 'python', 'python3', 'py') {
        if (Get-Command $py -ErrorAction SilentlyContinue) {
            & $py -c 'import esptool' 2>$null
            if ($LASTEXITCODE -eq 0) { $exe = $py; $preArgs = @('-m', 'esptool'); break }
        }
    }
}
if (-not $exe -and (Get-Command uv -ErrorAction SilentlyContinue)) {
    # Ephemeral uv-managed environment; no permanent install needed.
    $exe = 'uv'
    $preArgs = @('tool', 'run', 'esptool')
}
if (-not $exe) {
    Write-Error 'esptool was not found. Install it with:  uv tool install esptool  (or: pip install esptool)'
    exit 1
}

if (-not $Port) {
    $serialComm = Get-ItemProperty 'HKLM:\HARDWARE\DEVICEMAP\SERIALCOMM' -ErrorAction SilentlyContinue
    $ports = @($serialComm.PSObject.Properties |
        Where-Object { $_.Value -is [string] -and $_.Value -match '^COM\d+$' } |
        ForEach-Object { $_.Value } | Sort-Object -Unique)

    if ($ports.Count -eq 0) {
        Write-Error 'No serial port found. Put the board in bootloader mode (hold BOOT, tap RESET) and retry.'
        exit 1
    }
    if ($ports.Count -gt 1) {
        Write-Error "Multiple serial ports found ($($ports -join ', ')). Re-run with -Port <COMx>."
        exit 1
    }
    $Port = $ports[0]
    Write-Host ">> Auto-detected port: $Port"
}

$flashArgs = @(
    '--chip', 'esp32s3',
    '--port', $Port,
    '--baud', $Baud,
    'write_flash',
    '--flash-mode', 'dio',
    '--flash-freq', '80m',
    '--flash-size', '4MB'
)
foreach ($offset in $Images.Keys) { $flashArgs += @($offset, $Images[$offset]) }

Write-Host ">> Flashing $Environment to $Port at $Baud baud..."
& $exe @preArgs @flashArgs
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

Write-Host '>> Done. Tap RESET to run the new firmware.'
