#!/usr/bin/env sh
# Host-side firmware flasher (POSIX: Linux/macOS).
#
# The Docker build image cannot flash the board on macOS (no USB passthrough)
# and needs an explicit --device on Linux, so the simplest portable flow is:
# build in Docker, then flash the resulting artifacts from the host with esptool.
#
# Prerequisite:
#   uv tool install esptool        (or: pipx install esptool / pip install esptool)
#
# Usage:
#   ./build.sh                     # build in Docker first
#   ./flash.sh                     # auto-detect the serial port and flash
#   PORT=/dev/ttyACM0 ./flash.sh   # explicit port
#   BAUD=460800 ./flash.sh         # slower baud if 921600 is flaky
#
# Put the board in bootloader mode first: hold BOOT, tap RESET, release BOOT.
# (The single USB-C port is the USB-OTG port, and the firmware claims it for
# HID, so the board must be in ROM download mode to be flashable.)
#
# Linux users can alternatively flash straight from the build container:
#   docker run --rm -v "$PWD:/project" --device /dev/ttyACM0 \
#       switch-firmware-builder -t upload
set -eu

ENVIRONMENT=${ENVIRONMENT:-feather_s3_idf}
BAUD=${BAUD:-921600}

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
BUILD_DIR="$SCRIPT_DIR/.pio/build/$ENVIRONMENT"

# Offsets mirror .pio/build/<env>/flash_args generated by ESP-IDF.
BOOTLOADER="$BUILD_DIR/bootloader.bin"
PARTITIONS="$BUILD_DIR/partitions.bin"
FIRMWARE="$BUILD_DIR/firmware.bin"

for image in "$BOOTLOADER" "$PARTITIONS" "$FIRMWARE"; do
    if [ ! -f "$image" ]; then
        echo "Error: missing build artifact: $image" >&2
        echo "Run ./build.sh first." >&2
        exit 1
    fi
done

# esptool ships as `esptool.py` (v4) or `esptool` (v5); fall back to the module.
if command -v esptool.py >/dev/null 2>&1; then
    set -- esptool.py
elif command -v esptool >/dev/null 2>&1; then
    set -- esptool
elif command -v python3 >/dev/null 2>&1 && python3 -c 'import esptool' >/dev/null 2>&1; then
    set -- python3 -m esptool
elif command -v uv >/dev/null 2>&1; then
    # Ephemeral uv-managed environment; no permanent install needed.
    set -- uv tool run esptool
else
    echo "Error: esptool was not found. Install it with:  uv tool install esptool" >&2
    echo "                                          (or: pip install esptool)" >&2
    exit 1
fi

if [ -z "${PORT:-}" ]; then
    PORT=$(ls /dev/ttyACM* /dev/ttyUSB* /dev/cu.usbmodem* 2>/dev/null | head -n 2)
    case $(printf '%s\n' "$PORT" | grep -c .) in
        0) echo "Error: no serial port found. Put the board in bootloader mode (hold BOOT, tap RESET) and retry." >&2; exit 1 ;;
        1) echo ">> Auto-detected port: $PORT" ;;
        *) echo "Error: multiple serial ports found. Re-run with: PORT=/dev/... ./flash.sh" >&2; exit 1 ;;
    esac
fi

echo ">> Flashing $ENVIRONMENT to $PORT at $BAUD baud..."
"$@" --chip esp32s3 --port "$PORT" --baud "$BAUD" \
    write_flash --flash-mode dio --flash-freq 80m --flash-size 4MB \
    0x0 "$BOOTLOADER" \
    0x8000 "$PARTITIONS" \
    0x10000 "$FIRMWARE"

echo ">> Done. Tap RESET to run the new firmware."
